### ISSUE TITLE
follow selector does not work

### ISSUE THREAD

**Issue by CharlesJu1** [SanderLedegen/vscode-angular-follow-selector#1]
I am using VS Code 1.18.0. vscode-angular-follow-selector does not work. When I click on <app-root> selector, it does not do anything. Any configuration is needed?

**Comment by SanderLedegen** [comment]
No, it should work right out of the box; no configuration needed or even possible. I just tested it on version 1.18.0 as well and I don't see any irregularities.

Just to be sure, you Ctrl/Cmd+Click on a selector in HTML files, right? Does the other functionality like opening HTML and CSS files from a component work? And do you give the extension enough time to look for your definition? What happens when you move your mouse cursor over a component tag and hold Ctrl/Cmd? 😊

**Comment by CharlesJu1** [comment]
It does open HTML and CSS files from a component. In a component file, if I hold Ctrl and move the mouse over a HTML or CSS file, there is a underline showing and the tooltip showing. If I click, it takes me to the html or css file. But none of these happen on the component tag in a html file. When I click on the component tag in a html file, whether hold ctrl or not, it shows me the matching component tag, nothing else happens. Maybe the Ctrl + click is taken by some other plug in to show the matching tag?

**Comment by SanderLedegen** [comment]
OK, thanks for your feedback! That all looks good, though. Ctrl + Click could indeed be used by another extension, but then Ctrl + Clicking it would redirect you as well (by the other extension), and now nothing happens so there's just no action registered.

Anyway, according to your observations, it must have something to do with my code, and after a quick glance at my code, I might have a clue why! 😃 Is the format of the name of your components, by any chance, something like `*.component.ts`? I suspect this is not the case, which explains why my extension's not working in your project because I only consider files named in such format.

If you would be so kind, could you create a test component following this format (e.g. `test.component.ts`), give it a selector tag, use this test component somewhere in an HTML template and try clicking on it? I think (and hope!) this will resolve the issue. Or it won't, but it will at least rule out a possible cause on why this is happening.

Thanks and sorry for the inconvenience! 😊

**Comment by CharlesJu1** [comment]
I just added the first component in my angular project. The name is navbar-vertical.component.ts. It does follow the selector to the ts file for this component.  However, it does not follow the selectors from Angular Material, such as the <mat-sidenav-container> and <mat-sidenav>. Also in another big example Angular project that I downloaded, it does not follow the selectors defined by the program. The name of the component has the format of *.component.ts.

**Comment by SanderLedegen** [comment]
Alright, good to hear your own components can be found now! 👍

I created the extension so that it only searches for TS files in the workspace, not outside of it. The reason is because I thought most of the time that's what you'll be doing, checking your own components. You might _use_ other components but you don't need to know their inner plumbing; that's what documentation's for. But OK, perhaps it isn't a bad idea to extend this a little.

Also, it might be handy to add a setting to specify the file format of your components. Right now, I use Angular's [style guide](https://angular.io/guide/styleguide) concerning the (file) name of components. That's also the reason I mentioned this in the [requirements](https://github.com/SanderLedegen/vscode-angular-follow-selector#requirements).

Thanks for the feedback! 😃

**Comment by Chippi** [comment]
Doesn't seem to work for me either. When I ctrl + click a tag vscode gets stuck in loading state..
