### ISSUE TITLE
enable clicks on directives?

### ISSUE THREAD

**Issue by zzs1020** [SanderLedegen/vscode-angular-follow-selector#2]
Hi Sander, first thanks for the amazing plugin! It works like a charm for components.

But are you planning to implement the click-jump feature on attribute/structure directives? Can you kindly add this feature on top of this plugin, much appreciated!

i.e. I have ```<header app-header></header>``` instead of ```<app-header></app-header>```, but seems like it doesn't work by clicking 1st example directive.

**Comment by SanderLedegen** [comment]
Hi! First of all, sorry for the somewhat late response.

Truth to be told, I'm not reaaaally actively maintaining this little sideproject anymore but I've managed to include support for following directives as well! 🙌🏻I was also taking a quick look at following attributes but that feature isn't fully completed yet. I might finish it sometime 😊

Could you please let me know if this new version (1.2.0) works the way you intended concerning your given example? Thanks!

**Comment by zzs1020** [comment]
@SanderLedegen GM Sander, all our custom attribute directives are working properly, thanks! We don't have any custom structure directives so I can't test, but because it's rare case so that's fine so far! Thank you so much!

One more suggestion, **When you have time**, could you implement the feature that let people link from html to component by clicking on an instance variable? So far I can't find any plugin can do that. i.e. click ```{{someVariable}}``` or ```*ngFor="let a of someVariable"```, and it will bring you to component's someVariable declaration. This is extremely useful if you have inheritance for this component or it has relatively huger declaration list.

Thanks again!

**Comment by SanderLedegen** [comment]
Thanks for letting me know! 👍🏻

I know the capabilities of this extension are rather limited and it's getting harder and harder to add many more. That's because the way it works right now is actually not the way to go. I'm performing "dumb" searches through chunks of _text_ while a better alternative would be to actually _read_ and _parse_ the text as _code_. That way, there's a certain knowledge being built-up which allows more functionalities because the code is actually understood.

I'm not doing my own extension a favour by saying this but the Angular team has exactly done so by writing a language server. Such language server looks at your code, tries to understand the structure and everything and then provides you shortcuts etc. through an extension. You can find their extension [here](https://marketplace.visualstudio.com/items?itemName=Angular.ng-template) and I advise you to use that extension instead of mine since you want more functionality - I use it myself as well 🤭

The reason that I made this in the first place is that I didn't stumble upon an extension _back then_ that allowed me to do these things but at the moment, more than a year later, there are better alternatives. Even if that means that my extension is useless now 😊It was certainly a nice experience creating something that at least a few people use almost every day while getting feedback.

**Comment by zzs1020** [comment]
thanks!
